### ISSUE TITLE
Providing "option" function inside styles doesn't work

### ISSUE THREAD

**Issue by danberger1** [guiyep/react-select-virtualized#10]
If I want to change the style of the option component, I need to provide "option" function inside the styles prop.

something like - 

```
const customStyles = {
option: (provided, state) => {
    return {
    ...provided,
    borderBottom: '1px dotted pink',
    color: 'red',
    padding: 100,
      cursor: 'not-allowed'}
    }
}
...
<VirtualizedSelect styles={customStyles} />
```

In that case, the options new styles doesn't work. but other custom styles components, such as "control", do work.

**Comment by guiyep** [comment]
Please check the documentation in this repo. We do not support unfortunalty any prop or configuration of the options since they are completely custom.
