### ISSUE TITLE
Theme colors not working

### ISSUE THREAD

**Issue by malydok** [guiyep/react-select-virtualized#11]
For some reason it is impossible to override the default `theme.colors` object via the `theme` prop. The option label overflow is also handled differently and flows over the options below.

Please see the example comparing `react-select` to `react-select-virtualized` (3.0.4):
https://codesandbox.io/s/jovial-northcutt-szozc

**Comment by guiyep** [comment]
I will check it out and let you know!

Thanks for taking the time of opening the ticket!

**Comment by guiyep** [comment]
Hello,

Sorry for the delay. The library does not support any prop from the options. The theme won't apply to the options component. It is a whole new component. If you need to change the colors you will need to use css.

**Comment by guiyep** [comment]
One of the many reasons the react-select library is so bad performant is because they use styled-components.

**Comment by malydok** [comment]
Thanks for the tip and the timely response :-)
