### ISSUE TITLE
React Component as Option label

### ISSUE THREAD

**Issue by ktmn** [guiyep/react-select-virtualized#13]
Is there no way to custom render an option with this library?

I tried 

```jsx
<Select
    components={{
        Option: CustomOption,
    }}
/>
```

but it gets ignored/overridden?

I also tried

```jsx
<Select
    formatOptionLabel={option => {
        return option.label;
    }}
/>
```

but if I return anything other than a string then it crashes.

**Comment by guiyep** [comment]
Sorry mate, there is not, I override it for performance reasons.

**Comment by ktmn** [comment]
Thanks. 

I was able to use [this code](https://stackblitz.com/edit/react-select-v2-virtualized) with react-select v3 as a less performant fallback.
