### ISSUE TITLE
Disabling Options

### ISSUE THREAD

**Issue by mazarady** [guiyep/react-select-virtualized#130]
Hello. I hope you are well. I'm using this package and having difficulty disabling certain options. I've implemented the react-select method by trying the following returns on separate occasions 

`        return { value: brand, label: brand, disabled: 'yes' };
        return { value: brand, label: brand, disabled: true};
`
Is there a preferred method when using react-select-virtualized. Thanks

**Comment by guiyep** [comment]
Can you provide an example in a sandbox?

**Comment by guiyep** [comment]
I will be closing this since I did not have any response for the past week. We do not provide a disable property in the options. If that is the case create a custom option. Check the react select documentation for that.
