### ISSUE TITLE
Repeated options

### ISSUE THREAD

**Issue by zehawki** [guiyep/react-select-virtualized#131]
I have a large list (>40K options). At some point the selection will show dozens of duplicates which arnt actually there:

![image](https://user-images.githubusercontent.com/8095144/74089501-b5f68200-4ac7-11ea-896c-cba0a4307b72.png)

![image](https://user-images.githubusercontent.com/8095144/74089519-daeaf500-4ac7-11ea-88a9-456ccbaff264.png)

![image](https://user-images.githubusercontent.com/8095144/74089528-eb9b6b00-4ac7-11ea-8d58-b730a7e54d2f.png)

![image](https://user-images.githubusercontent.com/8095144/74089535-feae3b00-4ac7-11ea-9499-6c0cd381ee96.png)

**Comment by guiyep** [comment]
Can you provide an example in a sandbox?

**Comment by guiyep** [comment]
I will be closing in 2 days if I do not get any response.

**Comment by zehawki** [comment]
I looked into this carefully again in order to try to debug this issue and found that the reason for the repeats was something else, not related to your code. So closing this with thanks for a really useful piece of code and fantastic documentation that's rare to find :-)
