### ISSUE TITLE
missing blur() function / blurInputOnSelect

### ISSUE THREAD

**Issue by KX1095** [guiyep/react-select-virtualized#135]
In 'react-select' I have the option to control the focus with the `focus()` and `blur()` function shipped with the component ref. Here I missing the `blur()` function in the reference. I also tested the `blurInputOnSelect`-prop, but nothing happens. 
After selecting an option from the dropdown the control still focused. It's a problem for me, because I use custom styles for the query input field and the singleValue container based on the focus-state.

If there a way to fix it?

**Comment by guiyep** [comment]
I will make some tests and let you know.

**Comment by guiyep** [comment]
the Blur function is fixed in v #2.4.0. blurInputOnSelect is enabled by default.
