### ISSUE TITLE
Can't override option styles as you would with react-select

### ISSUE THREAD

**Issue by Jonny-B** [guiyep/react-select-virtualized#137]
The style object "option" should allow you to override the styles of each option in the dropdown list. Specifically in [THIS](https://codesandbox.io/s/vigilant-mclean-wpbk7?fontsize=14&hidenavigation=1&theme=dark) codesandbox example the background color. However, no styles are being applied.

**Comment by guiyep** [comment]
Please read the documentation for styling the options of the react-select-virtualised component. It is close to the end of the library readme file.
