### ISSUE TITLE
Module not found message in VS Code

### ISSUE THREAD

**Issue by M-Yankov** [guiyep/react-select-virtualized#14]
The following error message appears in VS Code.

> Could not find a declaration file for module 'react-select-virtualized'. 'd:/GitLab/SampleApps/ReactTest/ClientApp/node_modules/react-select-virtualized/dist/index.min.js' implicitly has an 'any' type.
  Try `npm install @types/react-select-virtualized` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-select-virtualized';`ts(7016)

The error is shown when hover over `from 'react-select-virtualized';`  
I've created a simple new react app with Visual Studio 2019 ASP .NET CORE with C# - only for scaffolding. Then navigated to the client side folder and opened VS Code and installed the `react-select-virtualized` package. The the following code:

```js
import React from 'react';
import { bindActionCreators } from 'redux';
import { connect } from 'react-redux';
import { actionCreators } from '../store/Counter';
import { Select } from 'react-select-virtualized';

const Counter = props => (
  <div>
    <h1>Counter</h1>

    <p>This is a simple example of a React component.</p>

    <p>Current count: <strong>{props.count}</strong></p>

    <button className="btn btn-primary" onClick={props.increment}>Increment</button>
    
    <Select 
     options={[ { label: 'test', value:'val'}]}>

    </Select>
  </div>
);

export default connect(
  state => state.counter,
  dispatch => bindActionCreators(actionCreators, dispatch)
)(Counter);
```

![image](https://user-images.githubusercontent.com/10440078/64949486-f982f200-d881-11e9-85aa-8b4790f998c2.png)

How to resolve the issue?

btw: the dropdown is working normally.

**Comment by guiyep** [comment]
Sorry mate this is not related to the library. But looks like you are missing some sort of file configurations. Also this is nos a typescript library but I guess that won’t affect.

**Comment by keemor** [comment]
@M-Yankov  Since it's not TS library add file **react-select-virtualized.d.ts**:

```
declare module 'react-select-virtualized';
```

Place it in the folder where your component and where you're importing react-select-virtualized
