### ISSUE TITLE
Filtering returning no results with filterOptions

### ISSUE THREAD

**Issue by janitarmila-ig** [guiyep/react-select-virtualized#140]
Filtering seems to be broken when filterOptions are given and there are enough elements. With only a few elements the filtering works fine, but after some low amount is reached, the search returns no results. Storybook example https://serene-hawking-021d7a.netlify.com/?path=/story/react-select-virtualized-props--with-filteroptions-value-with-number-less-than-1000 displays this behaviour even though https://serene-hawking-021d7a.netlify.com/?path=/story/react-select-virtualized-big-data--with-1000-elements works fine with more elements but no filterOptions.

**Comment by guiyep** [comment]
Can you provide an example in a sandbox?

**Comment by guiyep** [comment]
https://serene-hawking-021d7a.netlify.com/?path=/story/react-select-virtualized-props--with-filteroptions-value-with-number-less-than-1000 works as expected. That story expect to search `$$${number}` if you do so it will find the result.

**Comment by janitarmila-ig** [comment]
Looks like I found out what causes this, it's the fact that https://github.com/guiyep/react-select-virtualized/blob/3e88f7ce4d0a4a028cd066f1e8b1efbbd69338d4/src/lib/utils/index.js mapLowercaseLabel function returns the item like so:
`return { lowercaseLabel: label.toLowerCase(), ...item, ...iterator(item) };`

When the item has the label attribute defined with another name (via formatOptionLabel), the label attribute is only added as lowercaseLabel and not label, which in turn affected use in filterOption, when an assumption on the availability of label was made.

Closing this as a non-issue, since the label renaming is bound to cause problems anyway.
