### ISSUE TITLE
Clicking on vertical scroll bar closes menu in IE11

### ISSUE THREAD

**Issue by janitarmila-ig** [guiyep/react-select-virtualized#141]
Trying to scroll by clicking on the vertical scroll bar or arrows causes the dropdown to close on IE11. Could be something related to https://github.com/JedWatson/react-select/pull/3013 but this seems to work fine on the latest version of react-select, so probably has something to do with the customizations in react-select-virtualized.

**Comment by guiyep** [comment]
Can you show an example where it works in a plain react-select? I don’t think it is related to the menu modification in the library otherwise it may be showing some other react-select issue.

To be honest it is hard for me for testing on IE11 since I do not have any windows machine and it is pretty low priority for me fixing this type of issue. 

Does it work with Microsoft edge?

**Comment by janitarmila-ig** [comment]
I understand the issue with testing IE11 stuff, I wouldn't be supporting it myself if I had the choice, but due to legacy constraints it's unfortunately required.

All the examples on react-select.com seem to be functioning correctly on IE11 and Edge also works fine in both react-select and react-select-virtualized, as could be assumed.

I'll try to do some more digging to see what goes wrong and where.

**Comment by guiyep** [comment]
You can send me a PR if you want once you find the issue and I can merge it. Maybe there is some extra prop to set ? Or some event to stop propagating?

The main idea under my library was extending the container in the menu list and rebuild all the menu components in a Performant way. 

So essentially all of the components inside the menu list (options, list, etc) are extended using the components prop.

**Comment by janitarmila-ig** [comment]
I've managed to narrow things down to a point where it seems to be react-virtualized and probably its List that behaves strangely in IE11 (clicking on the scroll bar triggers blur event). There's a similar issue https://github.com/bvaughn/react-virtualized/issues/1323 open, but the workaround seems strange.

**Comment by guiyep** [comment]
Can we close the issue then?
