### ISSUE TITLE
Artifacting/layered on text in dropdown, known workaround

### ISSUE THREAD

**Issue by srohr** [guiyep/react-select-virtualized#144]
I'm using this library to provide a select for a little over 1000 elements, and noticed that some elements (like the one pictured below) have pretty illegible text.

![image](https://user-images.githubusercontent.com/6675481/75890197-04175080-5dfc-11ea-9a6c-cae2ba297ad7.png)

Interestingly enough, hovering these elements causes them to be perfectly legible.

I also found that adding a background color to the following CSS class solves this issue:

```css
.fast-option {
    background-color: white;
}
```

**Comment by guiyep** [comment]
Can you provide a codesandbox doc example?

**Comment by srohr** [comment]
Unfortunately I'm seeing this issue in code I'm writing for work, and my employer isn't one to allow us to post company data online, and the dropdown is full of company data. 

If this issue doesn't generally manifest in large (~1K options) dropdowns it might be more specific to my environment, I just wanted to let you all know that I'm seeing it and how I'm tackling it in case the issue shows up for others.

**Comment by guiyep** [comment]
that is fine, I will close this then and keep the solution in mind when someone rises it with a replicable example. thanks!
