### ISSUE TITLE
componentWillReceiveProps warning

### ISSUE THREAD

**Issue by Penguinatormike** [guiyep/react-select-virtualized#16]
update react-select from 3.0.4 => 3.0.5 in package.json

**Comment by Penguinatormike** [comment]
Updating should get rid of this message:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: AutosizeInput

**Comment by guiyep** [comment]
This is not an issue of this library. It is coming from `react-select` with react 16.9. Please follow this `react-select` issue that it is still open. https://github.com/JedWatson/react-select/issues/3720

You are using peer deps so you can use any version you want but the one recommended so far are specified in the readme.
