### ISSUE TITLE
Too long text for option

### ISSUE THREAD

**Issue by AntyfrizZz** [guiyep/react-select-virtualized#19]
Hello,

I have an issue when a text in an option is too log for one row. The text overlap with the rows bellow. Do you have a solution for that?
A link with a mockup example - https://codesandbox.io/s/weathered-dream-n5gqv
An image (if the mockup is not valid) 
![image](https://user-images.githubusercontent.com/6909862/66306167-a264c000-e909-11e9-9ba8-c64525f1648b.png)

Best Regards!

**Comment by guiyep** [comment]
Looks like a bug, I will fix it. But you can use css for fixing that for
now in your component and put an elipses in the text.

Thanks for reporting this!

**Comment by AntyfrizZz** [comment]
Hello,

Thank you for the fast response.
Can you give me an advice for the styling, because in the way I do it, the control breaks.
In the same mockup, there is a commented style in the style.css file. Can you please uncomment it and scroll down. Somewhere around number 109, the options disappear.

Best Regards!

**Comment by M-Yankov** [comment]
@guiyep  Is there any solution to this ? Can show an example ?

**Comment by guiyep** [comment]
Hello, there is but I cannot work on this right now. I’m working on other issue.

You can send a PR if you want Or fix it in your css until I have time to take a look. What you only have to do Is applying the ellipses text-overflow and overflow hidden to the css. I think that , that would fix the problem.

Let me know how it goes.

Thanks 

Check here: https://css-tricks.com/almanac/properties/t/text-overflow/

**Comment by AntyfrizZz** [comment]
Hello, guiyep,

Thank you for the provided solutions.
Unfortunately, ellipses style does solve the problem, but my business scenario requires the whole text to be seen.
If I come up with a solution, I will make PR.

Best Regards!

**Comment by guiyep** [comment]
Hello,

Sorry but that is not going to be possible. I understood that ellipses was enough. This component will not provide that feature, it is not a common scenario what you are asking for in a select component. You will have to implement it yourself.

React virtualised need a fixed height, so he can calculate what data need to be display based on the menu size.

Hope you find something that fits you.

Thanks,
Guiyep

**Comment by AntyfrizZz** [comment]
Hello,

Thank you for your response.

Best Regards!
