### ISSUE TITLE
Feature request to support Creatable 

### ISSUE THREAD

**Issue by nohns** [guiyep/react-select-virtualized#2]
Hi,

I wonder if you could add a creatable select component to this already great library?

**Comment by guiyep** [comment]
I will, I have it on my queue :).

**Comment by nohns** [comment]
> I will, I have it on my queue :).

Nice! Sounds cool, can you reply to this when it's ready? ;)

**Comment by guiyep** [comment]
Please keep track of this using this ticket that was already created https://github.com/guiyep/react-select-virtualized/issues/1

Will close this one.

Thanks,
Guille.
