### ISSUE TITLE
First option always hovered

### ISSUE THREAD

**Issue by hantaowang** [guiyep/react-select-virtualized#210]
![Screen Shot 2020-05-13 at 2 03 11 PM](https://user-images.githubusercontent.com/22207433/81865878-4a3b0f80-9523-11ea-8447-a88c5c069a50.png)

The first option in the list always has the hover effect, no matter what. This is not an issue with the latest react-select. It can be fixed by downgrading. 

Also, how come a selected option does not have color white like react-select? I was able to override styles but just wondering why black remains the default. 

Thanks for making this. Its very useful.

**Comment by guiyep** [comment]
Thanks for opening the issue,

Can you send me an example in a sandbox?

Thanks!

**Comment by hantaowang** [comment]
Sure. https://codesandbox.io/s/focused-swirles-itcr6?file=/package.json:124-125

Its a fork of your example sandbox with react-select-virtualized upgraded to 2.5.3

**Comment by mingzhaocn** [comment]
I have the same issue. 
Can you tell me which version you downgraded to fix it?

**Comment by mingzhaocn** [comment]
> I have the same issue.
> Can you tell me which version you downgraded to fix it?

react-select-virtualized@2.5.0 is ok

**Comment by guiyep** [comment]
Sorry guys, I have been very busy this week. I will come back to this next week. Thanks for the waiting.

**Comment by guiyep** [comment]
this should be fixed in 2.5.4.
