### ISSUE TITLE
First option always hovered (possible regression)

### ISSUE THREAD

**Issue by lushc** [guiyep/react-select-virtualized#233]
I'm experiencing the same issue noted in #210, I think [this commit](https://github.com/guiyep/react-select-virtualized/commit/9c01fc9c8afa65f4f806ac95c02f3f9072d158b7) caused a regression, because downgrading to 2.5.7 fixes the problem. Although I've noticed with that particular version that the first option doesn't have any styling applied when hovering over it.

**Comment by guiyep** [comment]
will take a look soon.

**Comment by guiyep** [comment]
I still need to take a look at this. I think it is related to react-select but I need to see if there is a workaround
