### ISSUE TITLE
formatGroupLabel doesn't work

### ISSUE THREAD

**Issue by sarates** [guiyep/react-select-virtualized#240]
I want to use `formatGroupLabel` for custom group styles, but all settings that are passed ignored.
I can't find any other way to change group name size (paddings) as all items in the list have `grouped-virtualized-list-item` class name. 
Also, would be nice to remove inline styles from list elements.

**Comment by guiyep** [comment]
Can you provide a sandbox example?

**Comment by guiyep** [comment]
I did not heard back. Please read the documentation:

`formatGroupHeaderLabel | function({ label, options}) => component`
