### ISSUE TITLE
Not building with NextJS

### ISSUE THREAD

**Issue by luknl** [guiyep/react-select-virtualized#271]
Hi! I installed this package on our Next.Js app, but I'm having this error when running `npm run dev`:
```
error - ./node_modules/react-virtualized/styles.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-select-virtualized/dist/index.min.js
```

I was able to fix this issue be removing `require("react-virtualized/styles.css")` in the file `node_modules/react-select-virtualized/dist/index.min.js`.

But it needs a better fix. In the errors there are some interesting link. Do you have an idea of how to fix this @guiyep?

Here is a [code sandbox](https://codesandbox.io/s/ancient-sunset-vq9kq?file=/pages/index.js) to see the bug.

Thank you!

Versions
```
"next": version 9.5.1
"react-virtualized": version 9.22.2
"react-select": version": 3.1.0
"react-select-virtualized": version": 2.5.10
```

**Comment by guiyep** [comment]
Hello,

This looks to be very specific to how Next.js works.

I cannot do much... if you want what you can do is cloning the repo and removing the require of the css. 
You will have to then add it after initialising your app.

Sorry mate, If I remove the require for you all the people using the library will need to require an extra file manually which is very annoying.

Cheers,
Guiyep

**Comment by luknl** [comment]
Yes, seem I have to do as you say. Others people did same with other libraries that trigger the same error with Next.js ([like here](https://github.com/lijinke666/react-music-player/issues/143#issuecomment-673907629))
Thanks for your answer!
Luca
