### ISSUE TITLE
prop defaultOptions as a boolean throws an error

### ISSUE THREAD

**Issue by arendoid** [guiyep/react-select-virtualized#273]
I want the data to load immediately when opening the list, for details see [**here**](https://react-select.com/async#defaultoptions) 

but unfortunately, I get this error when passing defaultOptions={true}
![image](https://user-images.githubusercontent.com/63283136/92439755-75c1c400-f1bc-11ea-9184-0575e29645c2.png)

**Comment by guiyep** [comment]
Sorry this is not supported, I will update the docs. We load them internally and based on the amount of data we load it async or not. Forcing this would breach the performance enhancements of this component.
