### ISSUE TITLE
onChange breaks tests

### ISSUE THREAD

**Issue by richardbross** [guiyep/react-select-virtualized#275]
Hello! I'm trying to mock the onChange function for a virtualized select dropdown.

```
  it('should skip disabled options', () => {

    const onChangeMock = jest.fn()
    const props = defaultProps({
      name: 'testSelect',
      value: options[0],
      displaySideButtons: true,
      onChange: onChangeMock,
      items: [options[0], {...options[1], isDisabled: true}, options[2]]
    })
    const wrapper = render(<Select {...props} />)

    const nextButton = wrapper.find('.select-next')
    nextButton.simulate('click')

    expect(onChangeMock).toHaveBeenCalledWith(options[2])

    wrapper.unmount()
  })
```

The above code results in the following errors all over my codebase...

`Error: Uncaught [TypeError: Cannot read property 'action' of undefined]`

**Comment by guiyep** [comment]
To be honest It is hard to tell. If u build the above example in a code sandbox. Does it works?

**Comment by richardbross** [comment]
Do you have any discrepancies around how onChange could be fired in a component passed to the components prop?

I'm decorating a select with previous and next arrows and when I click on the arrow it says:

`Error: Uncaught [TypeError: Cannot read property 'action' of undefined]`
