### ISSUE TITLE
It can't be integrated with Next.js

### ISSUE THREAD

**Issue by andreiaiova** [guiyep/react-select-virtualized#277]
I tried to use this library in a project that uses Next.js, and I received the following error:

Failed to compile
./node_modules/react-virtualized/styles.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/react-select-virtualized/dist/index.min.js

**Comment by guiyep** [comment]
Sorry but not sure why is that. It looks related to the next.js library not this component.

Is there anything I can do for helping you?

Integration with different libraries is outside the scope of why I built this open source project.

**Comment by justinforlenza** [comment]
Sorry to bump this old thread, didnt want to create another ticket about next.js,  but I was going to make a fork without the css import, but cant seem to find where in the code the CSS import is.
