### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by silviubogan** [guiyep/react-select-virtualized#282]
Hello!

I upgraded a project to React 17.0.2 from 16 and I see that react-select-virtualized does not support React 17 at the moment of this writing. Could you please solve this compatibility issue? I would do it in a PR but I don't have experience with this lib's code and I think I might break something.

This is a very good package. Thanks for making it.

**Comment by silviubogan** [comment]
I see that a matching version of React is used as a normal dependency, but not here:

https://github.com/guiyep/react-select-virtualized/blob/master/package.json#L92

Thanks.

**Comment by guiyep** [comment]
Sure will take a look. It shouldn’t be an issue to be honest react 17 should be backwards compatible. But let me do some testes

**Comment by guiyep** [comment]
Can you share a code sandbox showing the problem?

**Comment by silviubogan** [comment]
This is the error:

![image](https://user-images.githubusercontent.com/198924/120580583-1bdfe900-c432-11eb-99a1-8d4cbb8367ca.png)

These are the versions of the other relevant packages, besides React 17.0.2:

![image](https://user-images.githubusercontent.com/198924/120580848-83963400-c432-11eb-9e1f-8312b5911fdb.png)

[This](https://codesandbox.io/s/hardcore-greider-pnv15?file=/src/App.js) is a working CodeSandbox, since it is working I think that the problem is on my side.

Thanks!
