### ISSUE TITLE
Scrolling position support

### ISSUE THREAD

**Issue by Lukashev** [guiyep/react-select-virtualized#284]
So, for now we have auto scrolling to selected option ( index at the bottom ) . Also, I suggest to implement scrolling to the top (center ) of menu list. If you wanna get more information , please send me a hint .

**Comment by guiyep** [comment]
How the requirement would be?

**Comment by Lukashev** [comment]
@guiyep So,  look at this picture -> [https://ibb.co/v3bxKhZ](url) . If I choose an item that have another items after, selected object appears at the bottom of menu list. By the way, for example, we should set item visibility at the top of menu list, that's better UI. Library should support scrolling view behaviour (top, center, bottom) or smth else. How can i contact you ? It's important for me and maybe I can connect to project and fix that issue.

**Comment by Lukashev** [comment]
@guiyep also look Look https://www.loom.com/share/cf86a2374c074a51be08f1efcba23864. Can you fix this ?

**Comment by guiyep** [comment]
Hello @Lukashev sorry for the delay,

You can clone the repo and create a PR I will happily review it.

**Comment by guiyep** [comment]
I Will close for now, if you send a PR I'm more than happy to review it.
