### ISSUE TITLE
It fails if `regeneratorRuntime` isn't installed

### ISSUE THREAD

**Issue by fregante** [guiyep/react-select-virtualized#286]
Continuing the discussion from #283 

> This issue's conversation is now locked. If you want to continue this discussion please open a new issue.

The suggestion was not to bundle the regenerator runtime in this module but to drop the Babel transform that requires it. The size will go down, not up, because async functions will stay as async functions instead of being transpiled into regeneratorRuntime calls.

**Comment by fregante** [comment]
Side note: @devbots-lock-issue  is an awful idea

**Comment by guiyep** [comment]
Oh I see your point. I would accept a PR :).

**Comment by guiyep** [comment]
What is the baben transform that is requiering the module you are suggesting? “@babel/plugin-transform-runtime".

if I drop that and I that the browser list to latest 2, maybe that would solve the problem?

**Comment by fregante** [comment]
I think it's specifically `@babel/plugin-transform-async-to-generator` which is part of preset-env, but `plugin-transform-runtime` is _also_ not required. I see a few other babel dependencies that are either deprecated or unused as well. It might be a good idea to drop or update those (babel-loader is a webpack plugin and babel-preset-minify is deprecated)

**Comment by guiyep** [comment]
I just did and removed entirely the plugin-transform-runtime and fixed the browserlist. Let me know if that fixes the problem. You're right I need to clean up the rollup build, it is on my priority list :)

By the way, the package did go down! good call mate!

**Comment by fregante** [comment]
Let me check

**Comment by fregante** [comment]
https://www.unpkg.com/react-select-virtualized@3.2.0/dist/index.min.js

The code still has references to `regeneratorRuntime`. Also core-js should not be needed

**Comment by fregante** [comment]
This is likely due to old browsers still part of `last 2 versions`, like Opera mini and IE Mobile 10

```
npx browserslist 'last 2 versions, not ie <= 11'
npx: installed 6 in 2.828s
and_chr 91
and_ff 89
and_qq 10.4
and_uc 12.12
android 91
baidu 7.12
bb 10
bb 7
chrome 91
chrome 90
edge 91
edge 90
firefox 89
firefox 88
ie_mob 11
ie_mob 10
ios_saf 14.5-14.7
ios_saf 14.0-14.4
kaios 2.5
op_mini all
op_mob 62
op_mob 12.1
opera 77
opera 76
safari 14.1
safari 14
samsung 14.0
samsung 13.0
```

**Comment by guiyep** [comment]
So I have decided to include the runtime for now, with the browser list the impact on the package size shouldn't be too big. Will review the package's dependencies and see what I can improve. I do not want to remove more browser support, that means fewer people using this library. Let me know if it works now, I check the bundle and now it is initialized.

If you have any suggestion open a PR :), will be appreciated some help.

Thanks!

**Comment by guiyep** [comment]
let me know so I can close the ticket.

**Comment by fregante** [comment]
> So I have decided to include the runtime for now

As long as that stays constant during this major version, that's fine. 👍 Adding peer-dependency requirements would be a breaking change

**Comment by fregante** [comment]
I had misunderstood what you said, because it seems nothing has been changed and `regenerate-runtime` is still an undeclared dependency.

I found a solution that fixes the issue without changing the browser compatibility.

**Comment by guiyep** [comment]
fix merged.

**Comment by guiyep** [comment]
try 3.4.0
