### ISSUE TITLE
bump react to 17.x

### ISSUE THREAD

**Issue by pvrobays** [guiyep/react-select-virtualized#288]
While trying to use the library in our project we're stumbling upon the following error when running `npm i`:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.13.1" from react-select-virtualized@3.4.0
npm ERR! node_modules/react-select-virtualized
npm ERR!   react-select-virtualized@"^3.4.0" from the root project
```

react-select-virtualized version: `3.4.0` (latest at writing)
react version we use: `17.0.2` (latest at writing)
npm version : `7.19.1`

Seems like the library has a dependency to the previous react version?

**Workaround:**
run `npm i --legacy-peer-deps` instead to avoid errors with peer dependencies.

**Comment by guiyep** [comment]
I will fix the problem, I forgot to update the peer dependencies. This
package supports react 17. I will update them today.

**Comment by pvrobays** [comment]
Awesome @guiyep and thanks for the quick response.
Could you give an indication of when the new npm release would be available?

**Comment by guiyep** [comment]
done in 3.5.0
