### ISSUE TITLE
Could not find a declaration file for module 'react-select-virtualized'

### ISSUE THREAD

**Issue by vickramravichandran** [guiyep/react-select-virtualized#289]
The installed the package but the import statement displays an error

`import Select from "react-select-virtualized";`

> Could not find a declaration file for module 'react-select-virtualized'. 'c:/my-app/node_modules/react-select-virtualized/dist/index.min.js' implicitly has an 'any' type.
> Try `npm i --save-dev @types/react-select-virtualized` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-select-virtualized';`ts(7016)

I tried to install `npm i --save-dev @types/react-select-virtualized` but that does not exist on npm.

I am using typescript 4.3.5 with the following dependencies...

```
{
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-select": "^4.3.1",
    "react-select-virtualized": "^3.5.0",
    "react-virtualized": "^9.22.3"
}
```

**Comment by fregante** [comment]
While they might not be up to date, this fixes it partially:

```
npm install -D react-virtualized-select
```

```js
declare module "react-select-virtualized" {
  import VirtualizedSelect from "react-virtualized-select";
  export default VirtualizedSelect;
}
```

**Comment by fregante** [comment]
@guiyep It would still be great to have first-party support for types. My solution isn't perfect
