### ISSUE TITLE
Keyboard navigation in grouped mode not scrolling

### ISSUE THREAD

**Issue by Haemoglobin** [guiyep/react-select-virtualized#291]
Hi, 

Keyboard navigation works fine when not in grouped mode, i.e this example: https://serene-hawking-021d7a.netlify.app/?path=/story/react-select-virtualized-props--basic

However in grouped mode, when you hit the down keyboard arrow until you are at the bottom of the list and keep going, the scroll bar does not move down with you and stays where it is: https://serene-hawking-021d7a.netlify.app/?path=/story/react-select-virtualized-props--grouped-default

Is it possible to fix this or any workaround? 

I have also noticed in the basic example, if you keyboard navigate to the bottom of the list, and keep going, the selection wraps back to the top, however the scroll bar position does not so it is hidden, so it ends up looking like it has gone off the end with no selection. 

Thanks, 
Hamish

**Comment by guiyep** [comment]
I will need some time for investigating this.
