### ISSUE TITLE
Add TypeScript types 

### ISSUE THREAD

**Issue by fregante** [guiyep/react-select-virtualized#293]
The solution I suggested in https://github.com/guiyep/react-select-virtualized/issues/289#issuecomment-928738064 requires _stealing_ the types the unmaintained package that this is replacing.

For example, the old package imports types from `react-select` v3 that no longer exist in v5, like `ReactSelectProps` on line 8: https://unpkg.com/browse/@types/react-virtualized-select@3.0.11/index.d.ts

Could you include the types in this package? Or at least re-publish them in the `@types` repository under `react-select-virtualized`?

**Comment by guiyep** [comment]
If you publish a PR I can approve. Please remember to add a build for it so I can deploy it.

**Comment by guiyep** [comment]
won't do this is a Javascript project, not a Typescript project.
