### ISSUE TITLE
Select-Virtualized stop working after upgrade to latest version (5.3.0)

### ISSUE THREAD

**Issue by vasylHordynskyy** [guiyep/react-select-virtualized#315]
Hi,
First of all thanks for the great component.

We are using react-select virtualized in our project and after update to 5.3.0 it stoped working.
We got error: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `ForwardRef(Be)`. 

Here is example with error: [example](https://codesandbox.io/s/nervous-stitch-gzmp6q?file=/src/index.jsx)

Thanks in advance.

**Comment by guiyep** [comment]
Sorry for the delay I have been away. I will review this and fix the problem cheers.

**Comment by roildev** [comment]
Do we have some update here? I faced the same problem

**Comment by tarsdejaeger** [comment]
@guiyep  This is still an issue. 5.3.0 does not work

**Comment by guiyep** [comment]
I have finally had time to work on this, really sorry. I have reverted it and to 5.2.0 and bumped the version. If you install the latest (5.4.0) should be fixed. I will work on bumping all the packages versions to newer versions later.

**Comment by guiyep** [comment]
I will close this
