### ISSUE TITLE
jsnext:main is wrong and breaks eslint

### ISSUE THREAD

**Issue by scottc-netflix** [guiyep/react-select-virtualized#49]
This line is wrong in package.json

"jsnext:main": "dist/index.es.js"

This file doesn't exist, it should probably be `dist/index.min.es.js`

It still works with webpack but eslint can't resolve the package and throws errors because of this.

**Comment by guiyep** [comment]
You r right, I will fix this soon.

**Comment by guiyep** [comment]
Will be fixed in 2.3.2. It is in master and pushed to npm.
