### ISSUE TITLE
Navigation with arrow keys not working as with react-select

### ISSUE THREAD

**Issue by sondrehd** [guiyep/react-select-virtualized#51]
Probably not a bug, but it would be great if react-select-virtualized also had support for navigating through search results with the arrow keys in the same way react-select does.

**Comment by guiyep** [comment]
We support it. But react-select has an issue in their menu list that prevent me of enabling the feature.

Refer to this issue that also reference the react-select issue:

https://github.com/guiyep/react-select-virtualized/issues/17
