### ISSUE TITLE
Custom styling documentation

### ISSUE THREAD

**Issue by scottc-netflix** [guiyep/react-select-virtualized#60]
It's not clear how to override the styles, especially the option styles.

**Comment by scottc-netflix** [comment]
@guiyep 
I see there was another issue about styling options where you said "just use css". However, that doesn't seem possible as the names are minified even in dev mode, they appear like `css-1ivhyhq-control`, but then the hash in the middle changes in prod builds.

**Comment by guiyep** [comment]
I will add something to the Docs, I'm also thinking of creating a debug view. so It is easier to style since React-Select makes it very complex to do so.

thanks for reporting this

**Comment by guiyep** [comment]
doc updated
