### ISSUE TITLE
getOptionLabel broken with formatOptionLabel changes

### ISSUE THREAD

**Issue by janitarmila-ig** [guiyep/react-select-virtualized#64]
When getOptionLabel is used to change the default label attribute, react-select-virtualized crashes because of the changes introduced in 2.3.4 and #56. mapLowercaseLabel uses defaultFormatOptionLabel which accesses item.label directly even though item might not have an attribute named label at all.

**Comment by guiyep** [comment]
sorry about this, it is going to be fixed in v2.3.5
