### ISSUE TITLE
Node Version Requirement >= 9

### ISSUE THREAD

**Issue by gensc004** [guiyep/react-select-virtualized#7]
Is it possible to remove the requirement for Node being >= 9? I am currently on 8.x, and would like to avoid updating to start using the project if possible.

**Comment by guiyep** [comment]
Hello,

I’m not sure if it is possible. I don’t remember which package exactly has a dependency o the node version.

If you find it please submit a PR and I will be more than happy to merge it.

Thanks for taking the time,
Guiyep
