### ISSUE TITLE
Minified React Build formatOptionLabel returns something other than text error

### ISSUE THREAD

**Issue by agrin9002** [guiyep/react-select-virtualized#74]
I just ran a new build of an application that previously was working. The dev version worked fine in testing, but in prod some of the selectors cause this error to appear. I've checked the data being used as options and it is not null or undefined. What are the possible causes of this?

<img width="481" alt="Screen Shot 2019-11-27 at 10 03 02 AM" src="https://user-images.githubusercontent.com/53184859/69734569-2f074f80-10fd-11ea-8fe0-f8754ba5c560.png">

**Comment by guiyep** [comment]
If your formatOptionLabel returns a new component instead of just text, you need to have the label prop in the data. This is not related to a production build or not.

**Comment by guiyep** [comment]
I will close this since I did not have any response back.
