### ISSUE TITLE
getOptionLabel is still broken with formatOptionLabel changes

### ISSUE THREAD

**Issue by Vaculik** [guiyep/react-select-virtualized#98]
This issue #64 is closed, but the mentioned bug is still present. I have installed version `2.3.13`.

**Comment by guiyep** [comment]
Can you provide examples?

**Comment by guiyep** [comment]
A sandbox would be great. Thanks!

**Comment by guiyep** [comment]
Can you provide an example? Otherwise I will close this ticket since this was fixed already.

**Comment by themre** [comment]
hey, i just tested your library with latest react-virtualized and it works as expected. usually you need to filter out options empty strings/null/undefined. you can close the ticket and thanks for this nice library!

**Comment by guiyep** [comment]
Thanks!
